
#define IDI_ICON2			1

#define IDR_DRAWSHADER		500
#define IDR_MESHSHADER		510
#define IDR_PARTICLESHADER	520
#define IDR_WATERWARP		530
#define IDR_SPRITESHADER	540
#define IDR_SURFSHADER		550
#define	IDR_COMMON			600

